
version: '2'
services: 
    mongo:
        image: mongo
        container_name: mongo   
        ports: 
            - '27017:27017'

    mongo-seed:
        build: ./dbseed     
        links: 
        - mongo    
                            
    node: 
        container_name: node
        restart: always
        build: .
        ports:
            - '80:3000'
        links:
            - mongo







